version: "3.8"
services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        container_name: client_frontend_dev
        ports:
            - 3000:3000
        volumes:
            - "./frontend:/app:Z"
            - "/app/node_modules"
        stdin_open: true
        environment:
            - CHOKIDAR_USEPOLLING=true
        tty: true
    backend:
        build:
            context: ./backend
        container_name: client_backend_dev
        ports:
            - 8000:80
        volumes:
            - ./backend:/var/www/html
        stdin_open: true
