version: '3.8'
services:
  app:
    build: 
      context: ./backend
    container_name: backend_production
    tty: true
    networks:
      - labnet
  frontend:
    build: 
      context: ./frontend
    container_name: frontend_production
    networks:
      - labnet
  nginx:
    container_name: nginx
    restart: unless-stopped
    build: 
      context: ./server
    tty: true
    ports: 
      - 80:80
    volumes:
      - ./backend:/var/www/html/api
    networks:
      - labnet
    depends_on:
      - app
      - frontend
networks:
  labnet: