version: '3.8'
services:
  app:
    build: 
      context: ./backend
    container_name: backend_production
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ./backend:/var/www/html
    networks:
      - labnet
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports: 
      - "80:80"
    volumes:
      - ./backend:/var/www/html
      - ./backend/config/:/etc/nginx/conf.d/
    networks:
      - labnet
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - "./frontend:/app:Z"
      - "/app/node_modules"
    networks:
      - labnet
networks:
  labnet:
    external: true