version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: client_frontend_dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app:Z
      - /app/node_modules
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: client_backend_dev
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ./backend:/var/www/html
    stdin_open: true
    networks:
      - labnet
  nginx:
    container_name: nginx_dev
    restart: unless-stopped
    build: 
      context: ./server
    tty: true
    ports: 
      - 80:80
    volumes:
      - ./backend:/var/www/html
    networks:
      - labnet
    depends_on:
      - app
networks:
  labnet: