version: "3.8"
services:
    frontend:
        build:
            context: ./frontend
        container_name: client_frontend
        ports:
            - 3000:3000
        volumes:
            - "./frontend:/app:Z"
            - "./frontend/node_modules"
        stdin_open: true
        environment:
            - CHOKIDAR_USEPOLLING=true
    backend:
        build:
            context: ./backend
        container_name: client_backend
        ports:
            - 8000:80
        volumes:
            - ./backend:/var/www/html
        stdin_open: true
